### ISSUE TITLE
conda package is built as noarch, should be linux-64 now

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#137]
Note that this package is [published](https://anaconda.org/nsls2forge/hklpy) as `noarch`.  Also note that the underlying *hkl* package is [`linux-64`](https://anaconda.org/conda-forge/hkl).  Could be the underlying cause of #108, since we need to prevent this package from being conda installed in other OS.

This could be a critical issue before a conda-forge recipe (#136) is accepted.

**Comment by prjemian** [comment]
@mrakitin : Is this configuration located in the [nsls-ii-forge/hklpy-feedstock](https://github.com/nsls-ii-forge/hklpy-feedstock/blob/fc486c3ce05246d1b0042c02e0eb5724f7c43c18/recipe/meta.yaml#L15)?

```yaml
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
```

**Comment by prjemian** [comment]
Compare with similar [nsls-ii-forge/hkl-feedstock](https://github.com/nsls-ii-forge/hkl-feedstock/blob/master/recipe/meta.yaml#L15-L17):

```yaml
build:
  number: 2
  skip: True  # [py<36 or win or osx]
```
