### ISSUE TITLE
Upload built documentation as artifact

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#281]
@mrakitin suggests:

> ... useful to upload artifacts with the built docs, so that the rendering can be checked w/o running the build locally. [[see this example](https://github.com/NSLS-II/sirepo-bluesky/blob/39a7d09a3816f01396a4309149c0c2732606546a/.github/workflows/docs.yml#L96-L99)]

```yaml
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPOSITORY_NAME }}-docs
          path: docs/build/html/
```
