### ISSUE TITLE
Run a tiled server in the testing workflow

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#294]
Still need to run a tiled server in the testing workflow, then refactor to databroker v2.  So this PR is in draft mode ATM.

_Originally posted by @prjemian in https://github.com/bluesky/hklpy/issues/284#issuecomment-1791026416_

### Tasks
- [x] start MongoDB server - [0a20ebf](https://github.com/bluesky/hklpy/pull/295/commits/0a20ebf21313643a99dc3269f0da1d48b4bfe87c)
- [x] install database with bluesky catalogs for testing - not needed here, at least now
- [ ] Establish API key
- [x] start tiled server
- [ ] reconfigure `RE.subscribe()`
```

**Comment by prjemian** [comment]
At least two [options](https://duckduckgo.com/?q=github+action+MongoDB+server&t=brave&ia=web) for MongoDB server action:

- [mongodb-in-github-actions](https://github.com/marketplace/actions/mongodb-in-github-actions)
- [mongodb-for-github-actions](https://github.com/marketplace/actions/mongodb-for-github-actions)  - a fork from the one above

**Comment by prjemian** [comment]
Code examples from both show the same action:

```yaml
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
```

The second one has gone EOL.  So only one action now...
